- swagger.yaml
> Added version number to REST paths

- swagger.yaml
resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/35
> removed user deletion

- swagger.yaml
Fixes https://github.com/Metatavu/megasense-data-portal-api-spec/issues/37 and https://github.com/Metatavu/megasense-data-portal-api/pull/61
> added date-time format to the query parameters

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/39
> endpoint for getting air qualities for coordinates array

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/41
> added medical conditions to user settings

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/43
> init version of generic medical conditions

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/45
> Feature 45 generic pollutants

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/47
> replaced user settings object with user

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/51
> added object for total air quality data

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/53
> added air quality time parameter

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/55
> Feature 55 air quality requests time param

- swagger.yaml
Reverts Metatavu/megasense-data-portal-api-spec#58
> Revert "pollutant penalty sub schema added for medical conditions"

- swagger.yaml
> pollutant schema updated

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/63
> added default route endpoint, fixed pollutant penalties endpoint path

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/67
> Feature 67 jogging paths

- swagger.yaml
resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/69
> added transport preference field for user

- swagger.yaml
> pollutant unit

- swagger.yaml
> Feature 78 pollutant variable names

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/80
> Feature 80 favorite address

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/82
> Feature 82 route steps

- swagger.yaml
Resolves https://github.com/Metatavu/megasense-data-portal-api-spec/issues/90
> Mlup 28 feature 90 stripe payments api

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/92
> route history

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/94
> added one more status to stripe subscription

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/97
> added surname field

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/100
> Feature 100 new card registration

- swagger.yaml
> Changed subscription delete to cancel

- swagger.yaml
> Added card last 4 to user invoice object

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/104
> Feature 104 extended spec

- swagger.yaml
> home, work location added

- swagger.yaml
> Saved route location names

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/112
> added routeDistance as optional field to the saved route object

- swagger.yaml
> Added spec for passive exposure measurements

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/121
> added optional routeTime field

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/124
> Feature 124 time unit passive request

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/135
> mark time unit as required param

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/131
> route exposure

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/141
> pollutant color code 

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/137
> added field to pollutant

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/143
> move exposure measurement into the route creation

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/148
> rename stripe elements

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/150
> stripe trial specs

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/152
> Feature 152 email confirmation

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/154
> stripe prefix

- swagger.yaml
https://github.com/Metatavu/megasense-data-portal-api-spec/issues/156
> added additional response format for passive exposure measurements
